name: Sync Repo to GitLab

on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: keninkujovic/gitlab-synch@2.0.0
      with:
        gitlab_url: ${{ secrets.TARGET_URL }}
        username: ${{ secrets.TARGET_USERNAME }}
        gitlab_pat: ${{ secrets.TARGET_TOKEN }}
